# This workflow will install Python dependencies and run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run python-tests

on:
  push:
    branches: [main]
    paths: ["code/**"]
  pull_request:
    branches: [main]
    paths: ["code/**"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    env:
      working-directory: ./code

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f optional_requirements.txt ]; then pip install -r optional_requirements.txt; fi
      working-directory: ${{env.working-directory}}
    - name: Test with unittest
      run: |
        python -m unittest discover
      working-directory: ${{env.working-directory}}
